## CheckedContinuation
```swift
이전 챕터에서 사용자 정의 비동기 시퀀스를 만드는 과정을 거쳤다.
이를 통해 기본 API를 매핑하는것이 매우 강력하다는것을 보았는데.
이 챕터에서는 동일한 방향으로 계속해서 갈것이다.
Swift의 강력한 동시성 기능을 최대한 활용하여 기존 코드를 재사용하는
더 많은 방법들을 살펴 볼 것이다.

CheckedContinuation란 무엇인가
오랜시간동안 애플에서는 두가지 비동기 패턴이 주를 이뤘다
바로 completion 콜백 메서드와 Delegate 메서드 패턴이다.
새로운 동시성 모델의 채택을 촉진하기위해 Apple은 기존 코드를 연결할때 유용한 최소한의 강력한 API를 설계했다.
이는 continuation이라는 개념을 중심으로 한다.
continuation은 특정 시점에서 프로그램의 상태를 추적하는 객체이다.
Swift 동시성 모델은 각 비동기 작업 단위에 전체 스레드를 생성하는 대신 continuation을 할당한다.
이는 하드웨어의 기능에 따라 작업을 더 효과적으로 확장할수 있도록 해준다.
사용 가능한 CPU 코어 수만큼의 스레드만 생성하고, 스레드 대신 continuation 사이를 전환하여 실행을 더 효율적으로 만든다.

await 호출이 작동하는 방식은 익숙하다.
현재 코드가 실행이 중단되고 스레드 및 시스템 리소스가 CPU에 전달되어 다음 작업을 결정한다.
기존 코드가 중단되면 중단지점에서 캡쳐된 전체 상태를 나타내는 continuation이 생성된다.
실행을 재게하거나 예외를 throw 할때 동시성 시스템은 continuation과 작업에서 상태를 다시 생성한다.

이 모든것은 asnyc 함수를 사용할때 자동으로 발생한다.
또한 직접 continuation성을 생성하여 콜백이나, 델리게이트를 사용하는 기존 코드를 확장할수도 있다.
이러한 API는 await을 사용함으로써 이점을 얻을수 있다.
continuation을 수동으로 생성하면 기존 코드를 새로운 동시성 모델로 점진적으로 이전할수 있다.


continuation을 직접 생성하는 방법에는 두가지 API 변형이 존재한다.
- CheckedContinuation
중단된 실행을 재개하거나, 오류를 throw하는 매커니즘이다.
올바른 사용을 위한 런타임 체크를 제공하고 잘못된 사용을 로깅한다.
- UnSafeContiuation
CheckedContiuation의 대안으로 안전성 검사가 없다. 성능이 중요하고 추가적인 안정성은 필요없을때 사용한다.

참고로 API는 본질적으로 동일하므로 이 챕터에서는 CheckedContinuation만 다룰 것이다.

또한 일반적으로 직접적으로 continuation을 초기화 하지는 않는다. 대신 클로져를 매개변수로 제공하는 두가지 편리한 함수를 사용한다.

- withCheckedContiuation(_:)
- withCheckedThrowingContiuation(_:)
아래것이 그냥 에러를 던질수 있는 함수라고 생각하면된다.

continuation은 정호학히 한번만 재개하야한다.
이 규칙을 강제하는것이 Checked와 unSafe으 ㅣ차이이다.
다음과 같은 방법중 하나를 사용해 연속성을 재개한다.

resume(): 값을 반환하지 않고 중단된 작업을 재개한다.
resume(returning:): 중단된 작업을 재개하고 주어진 값을 반환한다.
resume(Throwing:): 제공된 오류를 throw 하며 중단된 작업을 재개한다.
resume(with:): 값 또는 오류를 포함하는 Result로 재개한다.

위의 메서드들은 continuation에 호출할수 있는 유일한 메서드들이며 더이상 사용하기 쉬운 최소한의 타입이다.
```

## Delegate 매핑
```swift
기존 코드를 재사용하기 위해 빠르게 continuation를 사용하는 방법을 배우기 위해 CLLocationManagerDelegate를 매핑해보자

먼저 다음 코드를 추가해 continuation을 생성해보자

        .task {
            do {
                let location: CLLocation = try await withCheckedThrowingContinuation { continuation in
                }
            } catch {

            }
        }

withCheckedThrowingContinuation는 예외를 던질수 있는 클로저를 받아서
현재 작업을 실시 중단한뒤에 클로저를 생성한다.
이 클로저안에서 비동기 코드를 호출하고 작업이 끝나면 continuation을 재개하면 된다.
이경우 위치데이터와 오류를 사용해서 continuation을 재개한다.
continuation는 다른 변수처럼 전달할수 있으며 모델에 저장하거나 다른 함수에 넘길수도 있다.
continuation이 어디있떤지 resume 메서드를 호출하면 항상 원래 호출 지점에서 실행이 재개된다.
또한 함수 이름에 checked가 포함되어 있는것을 볼수 있을것이다. 이는 런타임에 continuation을 안전하게 사용하는지 확인하는 용도다.
한번 프로젝트를 빌드해보자.
SWIFT TASK CONTINUATION MISUSE: body leaked its continuation!
라는 로그를 볼수 있다.

런타임이 continuation을 사용하지 않았고 클로저가 끝날때 변수가 해제되었음을 감지한것이다.
요약하자면 try await withCheckedThrowingContinuation(...)에서 코드는 일시 중단 지점에서 성공적으로 재개되지 않을 것이다.
앞서 언급했듯이 각 코드 경로에서 resum 메서드를 정확히 한번 호출해야한다.
다음으로 새로만든 델리게이트와 continuation을 통합하여 이문제를 해결해보자.

    private var continuation: CheckedContinuation<CLLocation, Error>?
    let manager = CLLocationManager()
    
두개의 프로퍼티를 가진 class를 하나 만들자
그리고 기본설정들을 해주자.

    private func configureInit() {
        manager.delegate = self
        manager.requestWhenInUseAuthorization()
        manager.requestAlwaysAuthorization()
    }

그 뒤 continuation을 전달할수 있는 함수를 만들자

    func setContinuation(continuation: CheckedContinuation<CLLocation, Error>?) {
        self.continuation = continuation
    }
    
그리고 위치정보를 받아오는 함수도 추가하자.
    func startUpdatingLocation() {
        manager.startUpdatingLocation()
    }
    
그리고 마지막으로 delegate에서 위치 정보를 받아온뒤에 이걸 continuation에 전달해보자
에러 또한 던질수가 있다.

    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        guard let location = locations.last else { return }
        continuation?.resume(returning: location)
        continuation = nil
    }

    func locationManager(_ manager: CLLocationManager, didFailWithError error: any Error) {
        continuation?.resume(throwing: error)
        continuation = nil
    }

그 뒤에 실제 사용하는곳에서 이렇게 사용하면 된다.
struct ContentView: View {
    let manager = LocationManager()

    @State var text: String = ""

    var body: some View {
        VStack {
            Text(text)

            Button("위치정보 받아오기") {
                Task {
                    do {
                        let location: CLLocation = try await withCheckedThrowingContinuation { continuation in
                            manager.setContinuation(continuation: continuation)
                            manager.startUpdatingLocation()
                        }
                        print("debug \(location)")
                        self.text = "\(location.altitude)"

                    } catch let error {
                        self.text = error.localizedDescription
                        print("debug \(error)")
                    }
                }
            }
        }
    }
}


버튼을 한번눌러보자. 이작업에는 두가지 결과가 있을것이다. 제대로 위치정보를 표시하거나 에러를 표시하거나
```

## 콜백 매핑
```swift
콜백기반 API를 한번 매핑해보자

struct ContentView: View {

    @State var text: String = ""
    @State var bool: Bool = false

    var body: some View {
        VStack {
            Text(text)

            Button("로그인") {
                Task {
                    let text: String = await withCheckedContinuation { continuation in
                        getText(isOnError: bool) { result in
                            switch result {
                            case .success(let text):
                                continuation.resume(returning: text)
                            case .failure(let error):
                                continuation.resume(returning: error.localizedDescription)
                            }
                        }
                    }
                    self.text = text
                    bool.toggle()
                }
            }
        }
    }

    private func getText(isOnError: Bool , completionHandler: @escaping (Result<String, Error>) -> ()) {
        DispatchQueue.global().asyncAfter(deadline: .now() + 2) {
            if isOnError {
                completionHandler(.failure(CustomError.defaultError))
            } else {
                completionHandler(.success("성공"))
            }
        }
    }
}

```

## 조금더 유연하게 한번 사용해보기
```swift
struct ContentView: View {

    let manager = TextManager()
    @State var text: String = ""

    var body: some View {
        VStack {
            Text(text)

            Button("로그인") {
                Task {
                    do {
                        let text = try await manager.getText()
                        self.text = text
                    } catch let error {
                        self.text = error.localizedDescription
                    }
                    manager.isOnError.toggle()
                }
            }
        }
    }

}

final class TextManager {

    var isOnError: Bool = false
    var continuation: CheckedContinuation<String, Error>?

    func getText() async throws -> String {
        try await withCheckedThrowingContinuation { [weak self] continuation in
            self?.continuation = continuation
            self?.fetchText()
        }
    }

    private func fetchText() {
        DispatchQueue.global().asyncAfter(deadline: .now() + 2) { [weak self] in
            guard let self else { return }
            if isOnError {
                continuation?.resume(throwing: CustomError.defaultError)
            } else {
                continuation?.resume(returning: "성공적")
            }
        }
    }
}
```


## 요약 정리
- 이전의 비동기적 설계패턴을 CheckedContinuation 또는 그것의 위험한 상대인 UnsafeCheckedContinuation을 사용하여 async/await로 연결할수 있다.    
- 각 코드 경로마다 값을 반환하거나 오류를 throw하기 위해 continuation의 resume(...) 메서드 중 하나를 정확히 한 번 호출해야 한다.    
- continuation을 얻으려면 withCheckedContinuation(:) 또는 withCheckedThrowingContinuation(:)을 호출해야한다.    
